version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/medicare_integrado
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: Bruno@8401


  db:
    image: postgres:13
    environment:
      POSTGRES_DB: medicare_integrado
      POSTGRES_USER: postgres
      POSTGRES_PASS: Bruno@8401
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
