version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db

    env_file:
      - .env
    environment:
      SPRING_DATASOURCE_URL: DB_URL=${DB_URL}
      SPRING_DATASOURCE_USERNAME: DB_USER=${DB_USER}
      SPRING_DATASOURCE_PASSWORD: DB_PASS=${DB_PASS}


  db:
    image: postgres:13
    env_file:
      - .env
    environment:
      POSTGRES_DB: medicare_integrado
      POSTGRES_USER: DB_USER=${DB_USER}
      POSTGRES_PASS: DB_PASS=${DB_PASS}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
