CREATE TABLE exam_schedule (
  id UUID PRIMARY KEY,
  datetime TIMESTAMP NOT NULL,
  status VARCHAR(20) NOT NULL, -- ENUM('SCHEDULED', 'CANCELLED', 'COMPLETED')
  patient_id UUID REFERENCES patient(id),
  exam_id UUID REFERENCES exam(id),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);