CREATE TABLE room (
  id UUID PRIMARY KEY,
  number VARCHAR(10) NOT NULL,
  floor INT,
  hospital_id UUID REFERENCES hospital(id),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);