CREATE TABLE bed (
  id UUID PRIMARY KEY,
  number VARCHAR(10) NOT NULL,
  room_id UUID REFERENCES room(id),
  occupied BOOLEAN NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);