CREATE TABLE patient (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        name VARCHAR(100) NOT NULL,
        cpf VARCHAR(11) NOT NULL,
        phone_number VARCHAR(20),
        email VARCHAR(100),
        data_nascimento DATE NOT NULL,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        address_id BIGINT NOT NULL,
        CONSTRAINT fk_address
            FOREIGN KEY (address_id)
            REFERENCES address(id)
)