CREATE TABLE plan (
  id UUID PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  operator_id UUID REFERENCES operator(id),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);