CREATE TABLE patient (
  id UUID PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  cpf VARCHAR(14) NOT NULL UNIQUE,
  phone VARCHAR(20),
  birth_date DATE,
  address_id UUID REFERENCES address(id),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);
