CREATE TABLE doctor (
  id UUID PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  crm VARCHAR(20) NOT NULL UNIQUE,
  specialty_id UUID REFERENCES specialty(id),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);